baseURL: 'https://kkso.github.io/'
languageCode: en-us
title: kkso's Writeups
theme: PaperMod
params:
  
    defaultTheme: dark
    disableThemeToggle: true
    ShowReadingTime: true 

    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "Currently Working on Hackthebox writeups"
        imageUrl: "/img/image1.png" # optional
        #imageTitle: "<title of image as alt>" # optional
        imageWidth: 250 # custom size
        imageHeight: 250 # custom size        
        buttons:
          - name: Archive
            url: "/archive"
    socialIcons:
    - name: email
      url: "mailto:kkwaste@mailfence.com"
    - name: hackthebox
      url: "https://app.hackthebox.eu/profile/632706"
    - name: github
      url: "https://github.com/kkso"
