baseURL: 'https://kkso.github.io/'
languageCode: en-us
title: kkso's Writeups
theme: PaperMod
params:
  
    defaultTheme: dark
    disableThemeToggle: true
    ShowReadingTime: true 


    profileMode:
        enabled: true
        title: "<Title>" # optional default will be site title
        subtitle: "Currently working on Hackthebox writeups"
        imageUrl: "/img/image3.png" # optional
        #imageTitle: "<title of image as alt>" # optional
        imageWidth: 256 # custom size
        imageHeight: 256 # custom size        
        buttons:
          - name: HackTheBox Writeups
            url: "/writeups/"
          - name: CVE Breakdowns
            url: "/cvebreakdowns/"
    socialIcons:
    - name: email
      url: "mailto:kkwaste@mailfence.com"
    - name: hackthebox
      url: "https://app.hackthebox.eu/profile/632706"
    - name: github
      url: "https://github.com/kkso"
menu:
  main:
  - identifier: Writeups
    name: HackTheBox Writeups
    url: "/writeups/"
    weight: 10
  - identifier: Breakdowns
    name: CVE Breakdowns
    url: "/cvebreakdowns/"
    weight: 10